### ISSUE TITLE
Templates are not configured

### ISSUE THREAD

**Issue by lumimario** [umbraco/Umbraco.Commerce.Checkout#15]
I have installed the package and all seems to be there except the templates. The pages that are created cannot be viewed because they are missing the templates.

Is there anything I need to do or is it a package issue?

Umbraco Version: 14.3.0
Umbraco.Commerce Version: 14.1.1
Umbraco.Commerce.Checkout Version: 14.0.0

**Comment by mattbrailsford** [comment]
The templates "should just work" so beyond intstalling, there shouldn't be anything you need to do to get them to work. Are you seeing any kind of errors anywhere?

**Comment by lumimario** [comment]
I was just getting a 404, and in the terminal I saw a 'Template cannot be found' message.

I have installed a new Umbraco site and now I'm not getting any errors but I'm redirected to the homepage when I try to navigate to any of the checkout pages. I haven't added a product or anything. Do I need this to be able to see the pages?

Sorry, I have the impression that I'm too new to this and I'm missing something silly.

**Comment by umbracotrd** [comment]
Hi @lumimario , I think you're missing few steps because you said that you hadn't added a product yet. The checkout pages do not work by themself, you need to add a product to the cart first for them to work.

You can check out this [over a minute internal demo video](https://photos.google.com/share/AF1QipMg2MiEgDG5bsVVA27iV2iut81IwX-wXn5h4NfFgUPxQyCK7eQd-6ynLQkxe1oJGg/photo/AF1QipNedPLdPddEyTqw9ndVxGKG-FsDLnvXL2ZxqMDc?key=NDFKaWpsN0NCNi1xNC0yazhhSlZXVzVDVDVFV1Vn)  to see the basic usage of this package.
At 0:30, you should see that I have Home page, product no 1 and product no 2 created manually before, you should create them by yourself on your site. Then, in the home page (any page will work, not only the home page), I have buttons to submit a form to add the product to cart. After that I can access the checkout page.

This is the controller action that adds a product to the cart.
```csharp
[HttpPost]
public IActionResult AddToCart(AddToCartDto postModel)
{
    try
    {
        _commerceApi.Uow.Execute(uow =>
        {
            StoreReadOnly store = CurrentPage!.GetStore() ?? throw new StoreDataNotFoundException();
            Order order = _commerceApi.GetOrCreateCurrentOrder(store.Id)
                .AsWritable(uow)
                .AddProduct(postModel.ProductReference, postModel.ProductVariantReference, 1);

            _commerceApi.SaveOrder(order);

            uow.Complete();
        });
    }
    catch (ValidationException ex)
    {
        ModelState.AddModelError("productReference", "Failed to add product to cart");

        return CurrentUmbracoPage();
    }

    TempData["addedProductReference"] = postModel.ProductReference;

    return RedirectToCurrentUmbracoPage();
}
```

**Comment by lumimario** [comment]
oh nice, thanks for that!

**Comment by umbracotrd** [comment]
I haven't heard from you in couple days so I'll close this issue now. If you need more help relate to this, feel free to open it
